name: Deploy to EKS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build & Push Docker image
      run: |
        IMAGE=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" -o eksctl.tar.gz
        tar -xzf eksctl.tar.gz
        sudo mv eksctl /usr/local/bin/
        eksctl version

    - name: Update kubeconfig
      run: |
        eksctl utils write-kubeconfig --region ${{ secrets.AWS_REGION }} --cluster ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/

    - name: Update deployment image
      run: |
        IMAGE=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
        kubectl set image deployment/inventory-app-deployment inventory-app=$IMAGE -n inventory-app

    - name: Wait for rollout
      run: |
        kubectl rollout status deployment/inventory-app-deployment -n inventory-app
